[platformio]
default_envs = circuitplayground_m0

[env:circuitplayground_m0]
platform = atmelsam@9.0.0
board = adafruit_circuitplayground_m0
framework = arduino
monitor_speed = 115200
build_flags = -DUSE_TINYUSB
lib_deps =
  adafruit/Adafruit Circuit Playground@1.12.0
