[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_src_filter = +<main.cpp>
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit GC9A01A
